### ISSUE TITLE
Models Deployment Error RuntimeError: Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by chasingw** [basicai/xtreme1#66]
error use detection model 
when I run `docker compose --profile model up`
```
xtreme1-redis-1                         | 1:M 30 Nov 2022 10:58:04.193 * Ready to accept connections
xtreme1-image-object-detection-1        | /opt/conda/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
xtreme1-image-object-detection-1        |   RequestsDependencyWarning)
xtreme1-point-cloud-object-detection-1  | 2022-11-30 10:58:05 INFO start_logger: -------------------- logging start --------------------
xtreme1-point-cloud-object-detection-1  | 2022-11-30 10:58:05 INFO start_logger: LEVEL: INFO
xtreme1-point-cloud-object-detection-1  | 2022-11-30 10:58:05 INFO start_logger: PATH:  /app/pcdet_open/server_logs/pid1
xtreme1-point-cloud-object-detection-1  | 2022-11-30 10:58:05 INFO start_logger: -------------------------------------------------------
xtreme1-point-cloud-object-detection-1  | 2022-11-30 10:58:05 INFO start_service: ----- SERVER STARTED -----
xtreme1-point-cloud-object-detection-1  | Tornado server starting on port 5000
xtreme1-image-object-detection-1        | test data convert to vgpu BEGIN
xtreme1-image-object-detection-1        | kk : tensor([0., 0., 0., 0.])
xtreme1-image-object-detection-1        | Traceback (most recent call last):
xtreme1-image-object-detection-1        |   File "server_abroad.py", line 35, in <module>
xtreme1-image-object-detection-1        |     tt = torch.zeros(4).cuda()
xtreme1-image-object-detection-1        |   File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 214, in _lazy_init
xtreme1-image-object-detection-1        |     torch._C._cuda_init()
xtreme1-image-object-detection-1        | RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

```
OS: ubuntu 18.04
GPU: GeForce RTX 2060
GPU driver version: 515.65.01
I do have installed NVIDIA Driver and NVIDIA Container Toolkit.
and nvidia-smi 
```
(base) ➜  xtreme1 git:(main) nvidia-smi
Wed Nov 30 19:03:30 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8     7W /  N/A |    364MiB /  6144MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2378      G   /usr/lib/xorg/Xorg                173MiB |
|    0   N/A  N/A      2604      G   /usr/bin/gnome-shell               67MiB |
|    0   N/A  N/A      3166      G   ...RendererForSitePerProcess       36MiB |
|    0   N/A  N/A      6922      G   ...AAAAAAAAA= --shared-files       62MiB |
|    0   N/A  N/A     11576      G   ...AAAAAAAAA= --shared-files       20MiB |
+-----------------------------------------------------------------------------+
```
and `docker run --rm --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi ` is also success
```
(base) ➜  xtreme1 git:(main) docker run --rm --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi       
Wed Nov 30 11:04:06 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8     5W /  N/A |    357MiB /  6144MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

```
and found another issue seems same error on Nvidia Tesla T4 https://github.com/basicai/xtreme1/issues/62, any suggestion about this? look forward for your reply, thanks!

**Comment by nicozhan** [comment]
Thanks for your question. We will update it to Readme doc.

**Enable model services**
Make sure you have installed [NVIDIA Driver](https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html) and [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker). But you do not need to install the CUDA Toolkit, as it already contained in the model image.

**Set "default-runtime" as "nvidia" in /etc/docker/daemon.json and restart docker to enable NVIDIA Container Toolkit**
```bash
{
  "runtimes": {
    "nvidia": {
      "path": "nvidia-container-runtime",
      "runtimeArgs": []
    }
  },
  "default-runtime": "nvidia"
}
```
**Need to explicitly specify model profile to enable model services.**
```bash
docker compose --profile model up
```

**Comment by chasingw** [comment]
> Thanks for your question. We will update it to Readme doc.
> 
> **Enable model services** Make sure you have installed [NVIDIA Driver](https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html) and [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker). But you do not need to install the CUDA Toolkit, as it already contained in the model image.
> 
> **Set "default-runtime" as "nvidia" in /etc/docker/daemon.json and restart docker to enable NVIDIA Container Toolkit**
> 
> ```shell
> {
>   "runtimes": {
>     "nvidia": {
>       "path": "nvidia-container-runtime",
>       "runtimeArgs": []
>     }
>   },
>   "default-runtime": "nvidia"
> }
> ```
> 
> **Need to explicitly specify model profile to enable model services.**
> 
> ```shell
> docker compose --profile model up
> ```

thanks for your help, I change the config and restart docker, but it doesn't work. and I check another docker to check my docker enviroment, it success
```
(base) ➜  xtreme1 git:(main) docker run --rm -it --gpus all tensorrt-ubuntu18.04-cuda11.4 bash                   
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

trtuser@f9bb9f074adb:/workspace$ python
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.Tensor().cuda()
tensor([], device='cuda:0')
```
but I check in the xtreme container it doesnt work,
```
(base) ➜  xtreme1 git:(main) docker ps
CONTAINER ID   IMAGE                                          COMMAND                  CREATED        STATUS                   PORTS                                                                                  NAMES
739269c3bdc4   basicai/xtreme1-point-cloud-object-detection   "python app.py ../cb…"   20 hours ago   Up 7 minutes             0.0.0.0:8293->5000/tcp, :::8293->5000/tcp

base) ➜  xtreme1 git:(main) docker exec -it 739269c3bdc4 /bin/bash
root@739269c3bdc4:/app/pcdet_open# python
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
False
>>> torch.Tensor().cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 214, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
>>> 
```
any suggestion about this?

**Comment by chasingw** [comment]
fixed by https://github.com/basicai/xtreme1/pull/68
